server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security?serverTimezone=Asia/Seoul
    username: cos
    password: 1234
    
# pom.xml 에 명시해두면 자동으로 설정되어 있으므로 생략
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update	#create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 458752518824-u8ei2dor04cdsf19lborlp5187i9g421.apps.googleusercontent.com
            client-secret: 4Wgyu56jtwH4ZNQdypApDdqU
            scope:
            - email
            - profile